[package]
name = "TwoSum"
version = "0.1.0"
edition = "2024"
description = "My Solution to 'Two Sum' Leetcode challenge"
readme = "README.md"
repository = "https://github.com/Collier-A-B/RustLeetcodeSolutions.git"
publish = false

[build]
target-dir = "target"

[dependencies]
